server:
  port: 9000
spring:
  application:
    name: fis-training-test-02
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-jwt-authentication?allowPublicKeyRetrieval=true&useSSL=false
    username: sa
    password: 123
  jpa:
    show-sql: true
    generate-ddl: true

quocdb:
  app:
    jwtSecret: quocdbSecretKey
    jwtExpirationMs: 86400000